version: "3.9"
services:
  job-board-frontend:
      build: ./client-angular
      image: job-board-frontend:latest
      container_name: job-board-frontend
      ports:
        - "4200:4200"
      depends_on:
        - job-board-backend
      networks:
        - job-board-network
  job-board-backend:
      build: ./server
      image: job-board-backend:latest
      container_name: job-board-backend
      restart: always
      ports:
        - "9001:9001"
      networks:
        - job-board-network
      environment:
        - OLLAMA_NUM_PARALLEL=4
        - OLLAMA_MAX_LOADED_MODELS=4 
        - LANGCHAIN_TRACING_V2="true"
        - LANGCHAIN_CALLBACKS_BACKGROUND="true"
        - NODE_ENV=production
        - EMAIL_USER=${EMAIL_USER}
        - EMAIL_PASS=${EMAIL_PASS}
        - JOB_BOARD_SECRET=${JOB_BOARD_SECRET}
        - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
        - OPENAI_API_KEY=${OPENAI_API_KEY}

networks:
  job-board-network:
    driver: bridge