name: Run tests

on:
  push:
    branches:
      - feature-*

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: cd server;npm install

    - name: Run tests with coverage
      run: cd server;npm run test