name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: cd server;npm install

    - name: Run tests with coverage
      run: cd server;npm run test

    - name: Install sshpass
      run: |
        sudo apt-get install -y sshpass

    - name: Stop containers
      run: |    
        sshpass -p '${{ secrets.HOSTNAME_PSWD }}' ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_LOGIN_STRING }} 'cd /home/eduardo/jobBoard && docker-compose down'    

    - name: Deploy to Remote Server
      run: |
        sshpass -p '${{ secrets.HOSTNAME_PSWD }}' ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_LOGIN_STRING }} <<'ENDSSH'
        export JOB_BOARD_SECRET=${{ secrets.JOB_BOARD_SECRET }}
        export LANGCHAIN_API_KEY=${{ secrets.LANGCHAIN_API_KEY }}
        export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        export EMAIL_USER=${{ secrets.EMAIL_USER }}
        export EMAIL_PASS=${{ secrets.EMAIL_PASS }}
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        cd /home/eduardo/jobBoard
        git checkout ${{ github.ref_name }}
        git pull
        docker-compose down
        docker-compose up --build -d
        ENDSSH
